INSERT INTO ACCOUNT_USER (ID, NAME, EMAIL, PASSWORD, ACTIVE, CREATED_AT, LAST_MODIFIED) VALUES (9996, 'Jorge Pereira', 'jorgepereira@teste.com.br', 'MTIzNDU2Nw==', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO ACCOUNT_USER (ID, NAME, EMAIL, PASSWORD, ACTIVE, CREATED_AT, LAST_MODIFIED) VALUES (9995, 'João Teixeira', 'joaoteixeira@teste.com.br', 'MTIzNDU2Nw==', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO ACCOUNT (ID, NUM, FK_ACCOUNT_USER, AMOUNT, ACTIVE, CREATED_AT, LAST_MODIFIED) VALUES (9999, '000001', 9995, 3000.0, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO ACCOUNT (ID, NUM, FK_ACCOUNT_USER, AMOUNT, ACTIVE, CREATED_AT, LAST_MODIFIED) VALUES (9998, '000002', 9996, 2000.0, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TRANSACTION (ID, TYPE, AMOUNT, TRANSFER_DATE, FK_DEPOSITOR, FK_RECEIVER, ACTIVE, CREATED_AT) VALUES (9997, 'D', 200.0, {ts '2022-05-23 18:00:00.00'}, 9999, 9998, TRUE, CURRENT_TIMESTAMP);
